{% set name = "ibis-framework" %}
{% set version = "2.1.1" %}

package:
  name: {{ name }}-ext
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15dc0c5d8abc41a9bddc643b7b360a61195d0363c61e83d2c588c55ff3b5b236

build:
  number: 1

requirements:
  host:
    - python >=3.7

outputs:
  - name: {{ name }}-core
    version: {{ version }}

    build:
      noarch: python
      script:
        # TODO: make this work without short-circuiting poetry
        - rm pyproject.toml || del pyproject.toml
        - python -m pip install . -vv --no-deps

    requirements:
      host:
        - pip
        - setuptools
        - python >=3.7

      run:
        - atpublic >=2.3
        - cached_property >=1
        - importlib-metadata >=4
        - multipledispatch >=0.6
        - numpy >=1.15
        - pandas >=1.2.5
        - python >=3.7
        - regex >=2021.7.6
        - toolz >=0.11
        - parsy >=1.3.0
        - python-graphviz >=0.16

    test:
      imports:
        - ibis
        - ibis.backends.pandas

  - name: {{ name }}
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - atpublic >=2.3
        - dask >=2021.10.0
        - datafusion >=0.4
        - pyarrow >=1
        - python >=3.7
        - python-graphviz >=0.16
        - requests >=2
        - sqlalchemy >=1.3
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.dask
        - ibis.backends.datafusion
        - ibis.backends.pandas
        - ibis.backends.sqlite


  - name: ibis-clickhouse
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - clickhouse-driver >=0.1.3
        - clickhouse-sqlalchemy >=0.1.4
        - sqlalchemy >=1.3
        - python >=3.7
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.clickhouse

  - name: ibis-dask
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pyarrow >=1
        - dask >=2021.10.0
        - python >=3.7
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.dask

  - name: ibis-hdf5
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pytables >=3
        - python >=3.7
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.hdf5

  - name: ibis-impala
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - impyla >=0.17
        - python-hdfs >=2.0.16
        - requests >=2
        - sqlalchemy >=1.3
        - python >=3.7
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.impala

  - name: ibis-mysql
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pymysql >=1
        - sqlalchemy >=1.3
        - python >=3.7
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.mysql

  - name: ibis-parquet
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pyarrow >=1
        - python >=3.7
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.parquet

  - name: ibis-postgres
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - sqlalchemy >=1.3
        - psycopg2 >=2.7
        - python >=3.7
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.postgres

  - name: ibis-pyspark
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pyarrow >=1
        - pyspark >=2.4.3
        - python >=3.7
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.pyspark

  - name: ibis-sqlite
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - sqlalchemy >=1.3
        - python >=3.7
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.sqlite

  - name: ibis-datafusion
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - datafusion >=0.4
        - python >=3.7
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.datafusion

about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: http://www.ibis-project.org
  summary: Productivity-centric Python Big Data Framework

extra:
  recipe-maintainers:
    - jreback
    - xmnlab
    - datapythonista
    - cpcloud
    - gforsyth
