{% set name = "ibis-framework" %}
{% set version = "5.0.0" %}

package:
  name: {{ name }}-ext
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 3ab78b08eeb0e7963df05fe3c21aa653d1f62d281e76e7542e2c52ac040e38eb

build:
  number: 0

requirements:
  host:
    - python >=3.8

outputs:
  - name: {{ name }}-core
    version: {{ version }}

    build:
      noarch: python
      script:
        # TODO: make this work without short-circuiting poetry
        - rm pyproject.toml || del pyproject.toml
        - python -m pip install . -vv --no-deps

    requirements:
      host:
        - pip
        - setuptools
        - python >=3.8

      run:
        - atpublic >=2.3
        - multipledispatch >=0.6
        - numpy >=1.15
        - pandas >=1.2.5
        - parsy >=1.3.0
        - pooch >=1.6.0
        - poetry-dynamic-versioning >=0.18.0
        - python >=3.8
        - python-graphviz >=0.16
        - regex >=2021.7.6
        - rich >=12.4.4
        - pytz >=2022.7
        - python-dateutil >=2.8.2
        - sqlglot >=10.4.3
        - toolz >=0.11

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.pandas

  - name: {{ name }}
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - duckdb-engine <1,>=0.1.8
        - python-duckdb <1,>=0.3.3
        - sqlalchemy <3,>=1.4
        - sqlalchemy-views <1,>=0.3.1
        - pyarrow <12,>=2
        - python-graphviz <1,>=0.16
        - {{ pin_subpackage(name + '-core') }}
    test:
      imports:
        - ibis
        - ibis.backends.duckdb


  - name: ibis-clickhouse
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - clickhouse-driver >=0.1.3
        - clickhouse-sqlalchemy >=0.1.4
        - sqlalchemy <2.0,>=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.clickhouse

  - name: ibis-dask
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - dask >=2022.9.1
        - pyarrow >=1
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.dask

  - name: ibis-impala
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - fsspec >=2022.1.0
        - impyla >=0.17
        - requests >=2
        - sqlalchemy <2.0,>=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.impala

  - name: ibis-mysql
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pymysql >=1
        - sqlalchemy <2.0,>=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.mysql

  - name: ibis-postgres
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - psycopg2 >=2.8.4
        - sqlalchemy <2.0,>=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.postgres

  - name: ibis-pyspark
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pyarrow >=2
        - pyspark >=3
        - sqlalchemy <2.0,>=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.pyspark

  - name: ibis-sqlite
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - sqlalchemy <2.0,>=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.sqlite

  - name: ibis-datafusion
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - datafusion >=0.6
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.datafusion

  - name: ibis-duckdb
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - duckdb-engine >=0.1.8
        - python-duckdb >=0.3.3
        - sqlalchemy-views >=0.3.1
        - sqlalchemy <2.0,>=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.duckdb

  - name: ibis-mssql
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pymssql >=2.2.5
        - sqlalchemy <2.0,>=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.mssql


  - name: ibis-bigquery
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - db-dtypes >=0.3.0,<2
        - google-cloud-bigquery >=3,<4
        - google-cloud-bigquery-storage >=2,<3
        - pyarrow >=2
        - pydata-google-auth
        - sqlalchemy <2.0,>=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.bigquery

  - name: ibis-trino
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - trino-python-client >=0.319.0
        - sqlalchemy <2.0,>=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.trino

  - name: ibis-snowflake
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - snowflake-connector-python >=2.7.10
        - snowflake-sqlalchemy >=1.4.1
        - sqlalchemy <2.0,>=1.4
        - pandas >=1.2.5
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.snowflake

  - name: ibis-polars
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name + '-core') }}
        - polars >=0.14

    test:
      imports:
        - ibis
        - ibis.backends.polars

  - name: ibis-druid
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name + '-core') }}
        - pydruid >=0.6.5
        - sqlalchemy <3,>=1.4
        - sqlalchemy-views <1,>=0.3.1

    test:
      imports:
        - ibis
        - ibis.backends.druid


about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: http://www.ibis-project.org
  summary: Productivity-centric Python Big Data Framework

extra:
  recipe-maintainers:
    - jreback
    - xmnlab
    - datapythonista
    - cpcloud
    - gforsyth
