{% set name = "ibis-framework" %}
{% set version = "10.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}-ext
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: c312f1590053d9eb35ce91d31216d21ec66fea4d519b6bb19001b3b30e3e7b3f

build:
  number: 0

requirements:
  host:
    - python {{ python_min }}

outputs:
  - name: {{ name }}-core
    version: {{ version }}

    build:
      noarch: python
      script:
        - find . -iname "snapshots" | xargs rm -r && python -m pip install . -vv --no-deps

    requirements:
      host:
        - pip
        - hatchling
        - python {{ python_min }}

      run:
        - atpublic >=2.3
        - bidict >=0.22.1
        - filelock >=3.7.0,<4
        - numpy >=1.23.2,<3
        - packaging >=21.3
        - pandas >=1.5.3,<3
        - parsy >=2
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - python >={{ python_min }}
        - python-graphviz >=0.16
        - regex >=2021.7.6
        - rich >=12.4.4,<14
        - pytz >=2022.7
        - python-dateutil >=2.8.2
        - sqlglot >=23.4,<26.4
        - toolz >=0.11,<1
        - typing-extensions >=4.3.0

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
      commands:
        - pip check


  - name: {{ name }}
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - python-duckdb >=0.10,<2
        - pins >=0.8.3,<1
        - fsspec

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.duckdb
      commands:
        - pip check


  - name: ibis-clickhouse
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - clickhouse-connect >=0.5.23

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.clickhouse
      commands:
        - pip check


  - name: ibis-impala
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - impyla >=0.17

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.impala
      commands:
        - pip check


  - name: ibis-mysql
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - mysqlclient >=2.2.4

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.mysql
      commands:
        - pip check


  - name: ibis-postgres
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - psycopg >=3.2.0,<4

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.postgres
      commands:
        - pip check


  - name: ibis-pyspark
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - pyspark >=3.3.3
        - packaging >=21.3,<25

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.pyspark
      commands:
        - pip check


  - name: ibis-sqlite
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - regex >=2021.7.6

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.sqlite
      commands:
        - pip check


  - name: ibis-datafusion
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - datafusion >=0.6

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.datafusion
      commands:
        - pip check


  - name: ibis-duckdb
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - python-duckdb >=0.10
        - pins >=0.8.3,<1
        - fsspec

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.duckdb
      commands:
        - pip check


  - name: ibis-mssql
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - pyodbc >=4.0.39

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.mssql
      commands:
        - pip check


  - name: ibis-bigquery
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - db-dtypes >=0.3.0,<2
        - google-cloud-bigquery >=3,<4
        - google-cloud-bigquery-storage >=2,<3
        - pydata-google-auth >=1.4.0,<2

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.bigquery
      commands:
        - pip check


  - name: ibis-trino
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - trino-python-client >=0.321

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.trino
      commands:
        - pip check


  - name: ibis-snowflake
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - snowflake-connector-python >=3.0.2

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.snowflake
      commands:
        - pip check


  - name: ibis-polars
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - polars >=1

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.polars
      commands:
        - pip check


  - name: ibis-druid
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - pydruid >=0.6.7

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.druid
      commands:
        - pip check


  - name: ibis-oracle
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - oracledb >=1.3.1

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.oracle
      commands:
        - pip check


  - name: ibis-exasol
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - pyexasol >=0.25.2

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.exasol
      commands:
        - pip check


  - name: ibis-flink
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - apache-flink
      commands:
        - pip check


    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.flink
      commands:
        - pip check


  - name: ibis-risingwave
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - psycopg2 >=2.8.4,<3

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.risingwave
      commands:
        - pip check


  - name: ibis-athena
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - pyathena >=3.11.0,<4
        - packaging >=21.3,<25
        - fsspec
        - s3fs
   
    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.athena
      commands:
        - pip check


  - name: ibis-databricks
    version: {{ version }}

    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - databricks-sql-connector-core >=4,<5

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - ibis
        - ibis.backends.databricks
      commands:
        - pip check


about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: http://www.ibis-project.org
  summary: The portable Python dataframe library

extra:
  recipe-maintainers:
    - jreback
    - xmnlab
    - datapythonista
    - cpcloud
    - gforsyth
