{% set version = "1.4.0" %}
{% set name = "ibis-framework" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb33e0d3ced3abecf7dde8e7cf159b235048eb29ee0752de829580f4cfc6e41d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - clickhouse-driver >=0.1.3
    - clickhouse-cityhash  # [not win]
    - clickhouse-sqlalchemy >=0.1.6
    - geoalchemy2
    - geopandas
    - google-cloud-bigquery-core >=1.12.0,<1.24.0dev
    - graphviz
    - impyla >=0.15.0
    - lz4
    - multipledispatch >=0.6
    - numpy >=1.15
    - pandas >=0.25.3
    - psycopg2
    - pyarrow >=0.15
    - pydata-google-auth
    - pymapd 0.24  # [py<38]
    - pymysql
    - pyspark >=2.4.3
    - pytables >=3.0.0
    - python
    - python-graphviz
    - python-hdfs >=2.0.16
    - pytz
    - regex
    - requests
    - shapely
    - setuptools
    - sqlalchemy >=1.1,<1.4
    - thrift >=0.11
    - thriftpy2
    - toolz

test:
  imports:
    - ibis
    - ibis.backends.bigquery
    - ibis.backends.clickhouse
    - ibis.backends.csv
    - ibis.backends.parquet
    - ibis.backends.hdf5
    - ibis.backends.impala
    - ibis.backends.mysql
    - ibis.backends.omniscidb  # [py<38]
    - ibis.backends.pandas
    - ibis.backends.postgres
    - ibis.backends.pyspark
    - ibis.backends.spark
    - ibis.backends.sqlite

about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: http://www.ibis-project.org
  summary: Productivity-centric Python Big Data Framework

extra:
  recipe-maintainers:
    - jreback
    - xmnlab
    - datapythonista
    - cpcloud
