{% set name = "ibis-framework" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}-ext
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c2266429123c9730307d75e1c2a778e4b9193c8c6d183a12b74c556a8ef9e3f

build:
  number: 5

outputs:
  - name: {{ name }}-core
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      noarch: python

    requirements:
      host:
        - pip
        - python >=3.7
        - setuptools

      run:
        - multipledispatch >=0.6
        - numpy >=1.15
        - pandas >=0.25.3
        - python >=3.7
        - pytz
        - regex
        - toolz
        - cached_property
        - setuptools
        - parsy
        - python-graphviz

    test:
      imports:
        - ibis
        - ibis.backends.pandas

  - name: {{ name }}
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      skip: true  # [py<37]

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - clickhouse-driver >=0.1.3
        - clickhouse-cityhash  # [not win]
        - clickhouse-sqlalchemy
        - geoalchemy2
        - geopandas
        - impyla >=0.17
        - lz4
        - psycopg2 >=2.7
        - pyarrow >=1.0
        - pymysql
        - pyspark >=2.4.3
        - pytables >=3.0.0
        - python
        - python-graphviz
        - python-hdfs >=2.0.16
        - requests
        - shapely
        - sqlalchemy >=1.3
        - thrift >=0.11
        - thriftpy2
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.clickhouse
        - ibis.backends.csv
        - ibis.backends.parquet
        - ibis.backends.hdf5
        - ibis.backends.impala
        - ibis.backends.mysql
        - ibis.backends.pandas
        - ibis.backends.postgres
        - ibis.backends.pyspark
        - ibis.backends.sqlite


  - name: ibis-clickhouse
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      skip: true  # [py<37]

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - clickhouse-driver >=0.1.3
        - clickhouse-cityhash  # [not win]
        - clickhouse-sqlalchemy >=0.1.4
        - sqlalchemy >=1.3
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.clickhouse

  - name: ibis-dask
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      skip: true  # [py<37]

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - lz4
        - pyarrow >=1
        - dask >=2021.2.0
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.dask

  - name: ibis-hdf5
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      skip: true  # [py<37]

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - pytables >=3.0.0
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.hdf5

  - name: ibis-impala
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      skip: true  # [py<37]

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - impyla >=0.15.0
        - python-hdfs >=2.0.16
        - requests
        - sqlalchemy >=1.3
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.impala

  - name: ibis-mysql
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      skip: true  # [py<37]

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - pymysql
        - sqlalchemy >=1.3
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.mysql

  - name: ibis-parquet
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      skip: true  # [py<37]

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - pyarrow >=1.0
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.parquet

  - name: ibis-postgres
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      skip: true  # [py<37]

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - sqlalchemy >=1.3
        - psycopg2 >=2.7
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.postgres

  - name: ibis-pyspark
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      skip: true  # [py<37]

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - lz4
        - pyarrow >=1.0
        - pyspark >=2.4.3
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.pyspark

  - name: ibis-sqlite
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      skip: true  # [py<37]

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - sqlalchemy >=1.3
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.sqlite

about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: http://www.ibis-project.org
  summary: Productivity-centric Python Big Data Framework

extra:
  recipe-maintainers:
    - jreback
    - xmnlab
    - datapythonista
    - cpcloud
    - gforsyth
