{% set name = "ibis-framework" %}
{% set version = "6.1.0" %}

package:
  name: {{ name }}-ext
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 1db6c23ff5cff8c2bea1ef3c77522763bb928becee7cfc3c1f5ee0d76b511440

build:
  number: 0

requirements:
  host:
    - python >=3.9

outputs:
  - name: {{ name }}-core
    version: {{ version }}

    build:
      noarch: python
      script:
        # TODO: make this work without short-circuiting poetry
        - rm pyproject.toml || del pyproject.toml
        - python -m pip install . -vv --no-deps

    requirements:
      host:
        - pip
        - setuptools
        - python >=3.9

      run:
        - atpublic >=2.3
        - bidict >=0.22.1
        - filelock >=3.7.0,<4
        - multipledispatch >=0.6
        - numpy >=1.15
        - pandas >=1.2.5
        - parsy >=2
        - pooch >=1.7.0
        - poetry-dynamic-versioning >=0.18.0
        - pyarrow >=2
        - python >=3.9
        - python-graphviz >=0.16
        - python-xxhash >=1.4.3
        - regex >=2021.7.6
        - rich >=12.4.4
        - pytz >=2022.7
        - python-dateutil >=2.8.2
        - sqlglot >=10.4.3
        - tqdm >=4.41.0,<5.0.0
        - toolz >=0.11

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.pandas

  - name: {{ name }}
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - duckdb-engine <1,>=0.1.8
        - python-duckdb <1,>=0.3.3
        - sqlalchemy <3,>=1.4
        - sqlalchemy-views <1,>=0.3.1
        - python-graphviz <1,>=0.16
        - {{ pin_subpackage(name + '-core') }}
        # - typing_extensions <5,>=4.3.0
        # - trino-python-client <1,>=0.321
        # - toolz <1,>=0.11
        # - sqlglot <18,>=10.4.3
        # - snowflake-sqlalchemy <2,>=1.4.1
        # - snowflake-connector-python <4,>=3.0.2
        # - shapely <3,>=2
        # - rich <14,>=12.4.4
        # - requests <3,>=2
        # - regex >=2021.7.6
        # - pytz >=2022.7
        # - python-dateutil <3,>=2.8.2
        # - pyspark <4,>=3
        # - pymysql <2,>=1
        # - pymssql <3,>=2.2.5
        # - pydruid <1,>=0.6.5
        # - pydata-google-auth <2,>=1.4.0
        # - pyarrow <13,>=2
        # - psycopg2 <3,>=2.8.4
        # - pooch <2,>=1.6.0
        # - polars <1,>=0.14.18
        # - parsy <3,>=2
        # - pandas <3,>=1.2.5
        # - packaging <24,>=21.3
        # - oracledb <2,>=1.3.1
        # - numpy <2,>=1
        # - multipledispatch <2,>=0.6
        # - impyla <1,>=0.17
        # - google-cloud-bigquery-storage <3,>=2
        # - google-cloud-bigquery <4,>=3
        # - geopandas <1,>=0.6
        # - fsspec >=2022.1.0
        # - filelock <4,>=3.7.0
        # - deltalake <1,>=0.9.0
        # - db-dtypes <2,>=0.3
        # - datafusion <28,>=0.6
        # - dask-core >=2022.9.1
        # - clickhouse-connect <1,>=0.5.23
        # - black <24,>=22.1.0
        # - bidict <1,>=0.22.1
        # - atpublic <5,>=2.3
        # - GeoAlchemy2 !=0.13.0,!=0.14.0,!=0.14.1,<1,>=0.6.3
    test:
      imports:
        - ibis
        - ibis.backends.duckdb


  - name: ibis-clickhouse
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - clickhouse-connect >=0.5.23
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.clickhouse

  - name: ibis-dask
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - dask >=2022.9.1
        - pyarrow >=1
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.dask

  - name: ibis-impala
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - fsspec >=2022.1.0
        - impyla >=0.17
        - requests >=2
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.impala

  - name: ibis-mysql
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pymysql >=1
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.mysql

  - name: ibis-postgres
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - psycopg2 >=2.8.4
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.postgres

  - name: ibis-pyspark
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pyarrow >=2
        - pyspark >=3
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.pyspark

  - name: ibis-sqlite
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.sqlite

  - name: ibis-datafusion
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - datafusion >=0.6
        - {{ pin_subpackage(name + '-core') }}

    test:
      requires:
        - packaging >=21.3
      imports:
        - ibis
        - ibis.backends.datafusion

  - name: ibis-duckdb
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - duckdb-engine >=0.1.8
        - python-duckdb >=0.3.3
        - sqlalchemy-views >=0.3.1
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.duckdb

  - name: ibis-mssql
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pymssql >=2.2.5
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.mssql


  - name: ibis-bigquery
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - db-dtypes >=0.3.0,<2
        - google-cloud-bigquery >=3,<4
        - google-cloud-bigquery-storage >=2,<3
        - pyarrow >=2
        - pydata-google-auth
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.bigquery

  - name: ibis-trino
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - trino-python-client >=0.319.0
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.trino

  - name: ibis-snowflake
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - snowflake-connector-python >=2.7.10
        - snowflake-sqlalchemy >=1.4.1
        - sqlalchemy >=1.4
        - pandas >=1.2.5
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.snowflake

  - name: ibis-polars
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name + '-core') }}
        - polars >=0.14

    test:
      imports:
        - ibis
        - ibis.backends.polars

  - name: ibis-druid
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name + '-core') }}
        - pydruid >=0.6.5
        - sqlalchemy >=1.4
        - sqlalchemy-views <1,>=0.3.1

    test:
      imports:
        - ibis
        - ibis.backends.druid

  - name: ibis-oracle
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name + '-core') }}
        - oracledb >=1.3.1
        - sqlalchemy >=1.4
        - sqlalchemy-views <1,>=0.3.1

    test:
      imports:
        - ibis
        - ibis.backends.oracle


about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: http://www.ibis-project.org
  summary: Productivity-centric Python Big Data Framework

extra:
  recipe-maintainers:
    - jreback
    - xmnlab
    - datapythonista
    - cpcloud
    - gforsyth
