{% set version = "1.3.0" %}

package:
  name: ibis-framework
  version: {{ version }}

source:
  url: https://github.com/ibis-project/ibis/archive/{{ version }}.tar.gz
  sha256: 36e0b2694a4e88a1406756eb32b21df7a625009f83bdfed012ab0159c7b49117

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  # uncomment noarch when pymapd and pyspark issues are fixed for py38
  # noarch: python

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - clickhouse-driver >=0.1.3
    - clickhouse-cityhash  # [not win]
    - clickhouse-sqlalchemy
    - geoalchemy2
    - geopandas
    - google-cloud-bigquery >=1.0.0
    - graphviz
    - impyla >=0.15.0
    - lz4
    - multipledispatch >=0.6
    - numpy >=1.11
    - pandas >=0.25
    - psycopg2
    - pyarrow >=0.13
    - pydata-google-auth
    - pymapd >=0.12.0  # [not py38]
    - pymysql
    - pyspark >=2.4.3  # [not py38]
    - pytables >=3.0.0
    - python
    - python-graphviz
    - python-hdfs >=2.0.16
    - pytz
    - regex
    - requests
    - shapely
    - setuptools
    - sqlalchemy >=1.1
    - thrift >=0.9.3
    - thriftpy2
    - toolz

test:
  imports:
    - ibis
    - ibis.bigquery
    - ibis.clickhouse
    - ibis.file.csv
    - ibis.file.parquet
    - ibis.file.hdf5
    - ibis.impala
    - ibis.sql.mysql
    - ibis.omniscidb  # [not py38]
    - ibis.pandas
    - ibis.sql.postgres
    - ibis.pyspark  # [not py38]
    - ibis.spark
    - ibis.sql.sqlite

about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: http://www.ibis-project.org
  summary: Productivity-centric Python Big Data Framework

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - wesm
    - kszucs
    - xmnlab
    - jreback
