{% set version = "0.13.0" %}
{% set tag = "v" + version %}
{% set extension = "tar.gz" %}
{% set fn = tag + "." + extension %}

package:
  name: ibis-framework
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://github.com/ibis-project/ibis/archive/{{ fn }}
  sha256: 3da1b51c72e074183abb08a2724a5b77f90e7328ab014de5ff7e699daf5c75f9

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - enum34  # [py27]
    - funcsigs  # [py27]
    - functools32  # [py27]
    - multipledispatch
    - numpy >=1.10.0
    - pandas >=0.18.1
    - python
    - regex
    - setuptools
    - six
    - toolz

  run:
    - clickhouse-driver >=0.0.8
    - enum34  # [py27]
    - funcsigs  # [py27]
    - functools32  # [py27]
    - google-cloud-bigquery <0.28
    - graphviz
    - impyla >=0.14.0
    - multipledispatch
    - numpy >=1.10.0
    - pandas >=0.18.1
    - pathlib2  # [py27]
    - psycopg2
    - pyarrow >=0.6.0  # [unix or (win64 and (py35 or py36))]
    - pymysql
    - pytables >=3.0.0
    - python
    - python-graphviz
    - python-hdfs >=2.0.16
    - regex
    - setuptools
    - six
    - sqlalchemy >=1.0.0,<1.1.15
    - thrift 0.9.3  # [py27]
    - thriftpy <=0.3.9  # [py27]
    - toolz

test:
  requires:
    - pytest >=3
    - mock  # [py27]
  imports:
    - ibis
    - ibis.expr
    - ibis.expr.tests
    - ibis.hive
    - ibis.hive.tests
    - ibis.impala  # [linux]
    - ibis.impala.tests  # [linux]
    - ibis.spark
    - ibis.spark.tests
    - ibis.sql
    - ibis.sql.presto
    - ibis.sql.presto.tests
    - ibis.sql.redshift
    - ibis.sql.redshift.tests
    - ibis.sql.sqlite
    - ibis.sql.sqlite.tests
    - ibis.sql.tests
    - ibis.sql.vertica
    - ibis.sql.vertica.tests
    - ibis.tests

about:
  license: Apache 2.0
  home: http://www.ibis-project.org
  summary: 'Productivity-centric Python Big Data Framework'

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - wesm
