{% set version = "0.12.0" %}  # TODO: 0.13.0

package:
  name: ibis-framework
  version: {{ version }}

source:
  fn: ibis-framework-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ibis-framework/ibis-framework-{{ version }}.tar.gz
  md5: b452f718ab8c607b01405e8ee40abf86  # TODO: update

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - enum34  # [py27]
    - graphviz
    - impyla >=0.14.0
    - multipledispatch
    - numpy >=1.10.0
    - pandas >=0.18.1
    - psycopg2
    - python
    - python-graphviz
    - python-hdfs >=2.0.16
    - setuptools
    - six
    - sqlalchemy >=1.0.0
    - thrift  # [py36]
    - thrift <=0.9.3  # [not py36]
    - thriftpy <=0.3.9
    - toolz

  run:
    - enum34  # [py27]
    - graphviz
    - impyla >=0.14.0
    - multipledispatch
    - numpy >=1.10.0
    - pandas >=0.18.1
    - psycopg2
    - python
    - python-graphviz
    - python-hdfs >=2.0.16
    - setuptools
    - six
    - sqlalchemy >=1.0.0
    - thrift  # [py36]
    - thrift <=0.9.3  # [not py36]
    - toolz

test:
  requires:
    - pytest >=3
    - mock  # [py27]
  imports:
    - ibis
    - ibis.expr
    - ibis.expr.tests
    - ibis.hive
    - ibis.hive.tests
    - ibis.impala  # [linux]
    - ibis.impala.tests  # [linux]
    - ibis.spark
    - ibis.spark.tests
    - ibis.sql
    - ibis.sql.presto
    - ibis.sql.presto.tests
    - ibis.sql.redshift
    - ibis.sql.redshift.tests
    - ibis.sql.sqlite
    - ibis.sql.sqlite.tests
    - ibis.sql.tests
    - ibis.sql.vertica
    - ibis.sql.vertica.tests
    - ibis.tests

about:
  license: Apache 2.0
  home: http://www.ibis-project.org
  summary: 'Productivity-centric Python Big Data Framework'

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - wesm
