{% set name = "ibis-framework" %}
{% set version = "3.2.0" %}

package:
  name: {{ name }}-ext
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 49d86a6cc32b91df057a30e8729b530e261bd5b49bce55736796acc64da72cc8

build:
  number: 0

requirements:
  host:
    - python >=3.8

outputs:
  - name: {{ name }}-core
    version: {{ version }}

    build:
      noarch: python
      script:
        # TODO: make this work without short-circuiting poetry
        - rm pyproject.toml || del pyproject.toml
        - python -m pip install . -vv --no-deps

    requirements:
      host:
        - pip
        - setuptools
        - python >=3.8

      run:
        - atpublic >=2.3
        - cached_property >=1
        - importlib-metadata >=4
        - multipledispatch >=0.6
        - numpy >=1.15
        - packaging >=21.3
        - pandas >=1.2.5
        - parsy >=1.3.0
        - poetry-dynamic-versioning >=0.14.0
        - pydantic >=1.9.0
        - python >=3.8
        - python-graphviz >=0.16
        - regex >=2021.7.6
        - rich >=12.4.4,<13
        - tabulate >=0.8.9
        - toolz >=0.11

    test:
      imports:
        - ibis
        - ibis.backends.pandas

  - name: {{ name }}
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - atpublic <4,>=2.3
        - dask >=2021.10.0
        - datafusion <0.7,>=0.4
        - duckdb-engine <1,>=0.1.8
        - pyarrow <10,>=1
        - python-duckdb <1,>=0.3.2
        - python-graphviz <0.21,>=0.16
        - sqlalchemy <2.0,>=1.4
        - {{ pin_subpackage(name + '-core') }}
        # - toolz <0.13,>=0.11
        # - tabulate <1,>=0.8.9
        # - shapely <1.8.3,>=1.6
        # - requests <3,>=2
        # - regex >=2021.7.6
        # - pyspark <4,>=3
        # - pymysql <2,>=1
        # - pydantic <2,>=1.9.0
        # - psycopg2 <3,>=2.8.4
        # - parsy <2,>=1.3.0
        # - pandas <2,>=1.2.5
        # - packaging <22,>=21.3
        # - numpy <2,>=1
        # - multipledispatch <0.7,>=0.6
        # - lz4 <5,>=3.1.10
        # - impyla <0.19,>=0.17
        # - geopandas <0.12,>=0.6
        # - geoalchemy2 <0.13,>=0.6.3
        # - fsspec >=2022.1.0
        # - dask-core >=2021.10.0
        # - clickhouse-driver <0.3,>=0.1
        # - clickhouse-cityhash <2,>=1.0.2
        # - toolz <0.13,>=0.11
        # - sqlglot <7,>=4.5.0
        # - shapely <1.8.5,>=1.6
        # - rich <13,>=12.4.4
        # - requests <3,>=2
        # - regex >=2021.7.6
        # - pyspark <4,>=3
        # - pymysql <2,>=1
        # - pydantic <2,>=1.9.0
        # - psycopg2 <3,>=2.8.4
        # - parsy <3,>=1.3.0
        # - pandas <2,>=1.2.5
        # - packaging <22,>=21.3
        # - numpy <2,>=1
        # - multipledispatch <0.7,>=0.6
        # - lz4 <5,>=3.1.10
        # - impyla <0.19,>=0.17
        # - geopandas <0.12,>=0.6
        # - geoalchemy2 <0.13,>=0.6.3
        # - fsspec >=2022.1.0
        # - dask-core <2022.8.0,>=2021.10.0
        # - clickhouse-driver <0.3,>=0.1
        # - clickhouse-cityhash <2,>=1.0.2

    test:
      imports:
        - ibis
        - ibis.backends.dask
        - ibis.backends.datafusion
        - ibis.backends.duckdb
        - ibis.backends.pandas
        - ibis.backends.sqlite


  - name: ibis-clickhouse
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - clickhouse-driver >=0.1.3
        - clickhouse-sqlalchemy >=0.1.4
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.clickhouse

  - name: ibis-dask
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - dask >=2021.10.0
        - pyarrow >=1
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.dask

  - name: ibis-impala
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - fsspec >=2022.1.0
        - impyla >=0.17
        - python-hdfs >=2.0.16
        - requests >=2
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.impala

  - name: ibis-mysql
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pymysql >=1
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.mysql

  - name: ibis-postgres
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - psycopg2 >=2.7
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.postgres

  - name: ibis-pyspark
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pyarrow >=1
        - pyspark >=2.4.3
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.pyspark

  - name: ibis-sqlite
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.sqlite

  - name: ibis-datafusion
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - datafusion >=0.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.datafusion

  - name: ibis-duckdb
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - duckdb-engine
        - python-duckdb
        - sqlalchemy >=1.4
        - {{ pin_subpackage(name + '-core') }}

    test:
      imports:
        - ibis
        - ibis.backends.duckdb

about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: http://www.ibis-project.org
  summary: Productivity-centric Python Big Data Framework

extra:
  recipe-maintainers:
    - jreback
    - xmnlab
    - datapythonista
    - cpcloud
    - gforsyth
