{% set version = "1.2.0" %}

package:
  name: ibis-framework
  version: {{ version }}

source:
  url: https://github.com/ibis-project/ibis/archive/{{ version }}.tar.gz
  sha256: 9def01ba183ec235a28ff404d3065d9eb214f81dd5dd9f3fed458e94e7e16271

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3
    - setuptools

  run:
    - clickhouse-driver >=0.0.8
    - geoalchemy2
    - geopandas
    - google-cloud-bigquery >=1.0.0
    - graphviz
    - impyla >=0.15.0
    - lz4
    - multipledispatch >=0.6
    - numpy >=1.11
    - pandas >=0.21
    - psycopg2
    - pyarrow >=0.12
    - pydata-google-auth
    - pymapd >=0.12.0
    - pymysql
    - pytables >=3.0.0
    - python >=3
    - python-graphviz
    - python-hdfs >=2.0.16
    - pytz
    - regex
    - requests
    - setuptools
    - shapely
    - sqlalchemy >=1.1
    - thrift >=0.9.3
    - thriftpy2
    - toolz

test:
  requires:
    - pytest >=4.5
  source_files:
    - ibis
    - conftest.py
    - setup.cfg
  commands:
    - pytest --rootdir ibis -m "not (backend or bigquery or clickhouse or hdfs or impala or kudu or mapd or mysql or postgresql or superuser or udf or postgis)" --ignore ibis/tests/test_version.py --tb=line

about:
  license: Apache 2.0
  home: http://www.ibis-project.org
  summary: 'Productivity-centric Python Big Data Framework'

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - wesm
    - kszucs
    - xmnlab
