{% set name = "ibis-framework" %}
{% set version = "9.3.0" %}

package:
  name: {{ name }}-ext
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 5e098318964d7ce53218ba9dcbf4b90d127ca3aea5fdf71661d03dc610d5df49

build:
  number: 1

requirements:
  host:
    - python >=3.10

outputs:
  - name: {{ name }}-lite
    version: {{ version }}

    build:
      noarch: python
      script:
        - find . -iname "snapshots" | xargs rm -r && python -m pip install . -vv --no-deps
      script_env:
        - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}

    requirements:
      host:
        - pip
        - poetry-core >=1.0.0
        - poetry-dynamic-versioning >=0.18.0
        - python >=3.10

      run:
        - atpublic >=2.3
        - parsy >=2
        - python >=3.10
        - regex >=2021.7.6
        - rich >=12.4.4
        - pytz >=2022.7
        - python-dateutil >=2.8.2
        - sqlglot >=23.4,<25.10
        - toolz >=0.11

    test:
      imports:
        - ibis

  - name: {{ name }}-core
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - numpy >=1.23.2,<3
        - pandas >=1.5.3
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - python-graphviz >=0.16
        - {{ pin_subpackage(name + '-lite', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.pandas
    
  - name: {{ name }}
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - python-duckdb <2,>=0.8.1
        - pins <1,>=0.8.3
        - fsspec <2024.6.2
        # - typing_extensions <5,>=4.3.0
        # - trino-python-client <1,>=0.321
        # - toolz <1,>=0.11
        # - sqlglot <25.2,>=23.4
        # - snowflake-connector-python !=3.3.0b1,<4,>=3.0.2
        # - shapely <3,>=2
        # - rich <14,>=12.4.4
        # - regex >=2021.7.6
        # - pytz >=2022.7
        # - python-graphviz <1,>=0.16
        # - python-dateutil <3,>=2.8.2
        # - pyspark <4,>=3
        # - pyodbc <6,>=4.0.39
        # - pymysql <2,>=1
        # - pyexasol <1,>=0.25.2
        # - pydruid <1,>=0.6.7
        # - pydata-google-auth <2,>=1.4.0
        # - pyarrow-hotfix <1,>=0.4
        # - pyarrow <17,>=10.0.1
        # - psycopg2 <3,>=2.8.4
        # - polars <1,>=0.20.17
        # - parsy <3,>=2
        # - pandas <3,>=1.5.3
        # - packaging <25,>=21.3
        # - oracledb <3,>=1.3.1
        # - numpy <2,>=1.23.2
        # - impyla <1,>=0.17
        # - google-cloud-bigquery-storage <3,>=2
        # - google-cloud-bigquery <4,>=3
        # - geopandas <1,>=0.6
        # - deltalake <1,>=0.9.0
        # - db-dtypes <2,>=0.3
        # - datafusion <39,>=0.6
        # - dask-core <2024.3.0,>=2022.9.1
        # - clickhouse-connect <1,>=0.5.23
        # - black <25,>=22.1.0
        # - bidict <1,>=0.22.1
        # - atpublic <5,>=2.3
        # - typing_extensions <5,>=4.3.0
        # - trino-python-client <1,>=0.321
        # - toolz <1,>=0.11
        # - sqlglot <25.7,>=23.4
        # - snowflake-connector-python !=3.3.0b1,<4,>=3.0.2
        # - shapely <3,>=2
        # - rich <14,>=12.4.4
        # - regex >=2021.7.6
        # - pytz >=2022.7
        # - python-graphviz <1,>=0.16
        # - python-dateutil <3,>=2.8.2
        # - pyspark <4,>=3.3.3
        # - pyproj <4,>=3.3.0
        # - pyodbc <6,>=4.0.39
        # - pymysql <2,>=1
        # - pyexasol <1,>=0.25.2
        # - pydruid <1,>=0.6.7
        # - pydata-google-auth <2,>=1.4.0
        # - pyarrow-hotfix <1,>=0.4
        # - pyarrow <18,>=10.0.1
        # - psycopg2 <3,>=2.8.4
        # - polars <2,>=1
        # - parsy <3,>=2
        # - pandas <3,>=1.5.3
        # - packaging <25,>=21.3
        # - oracledb <3,>=1.3.1
        # - numpy <3,>=1.23.2
        # - impyla <1,>=0.17
        # - google-cloud-bigquery-storage <3,>=2
        # - google-cloud-bigquery <4,>=3
        # - geopandas <2,>=0.6
        # - geoarrow-types <1,>=0.2
        # - deltalake <1,>=0.9.0
        # - db-dtypes <2,>=0.3
        # - datafusion <40,>=0.6
        # - dask-core <2024.3.0,>=2022.9.1
        # - clickhouse-connect <1,>=0.5.23
        # - black <25,>=22.1.0
        # - atpublic <5,>=2.3
    test:
      imports:
        - ibis
        - ibis.backends.duckdb


  - name: ibis-clickhouse
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - clickhouse-connect >=0.5.23
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.clickhouse


  - name: ibis-impala
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - impyla >=0.17
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.impala

  - name: ibis-mysql
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pymysql >=1
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.mysql

  - name: ibis-postgres
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - psycopg2 >=2.8.4
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.postgres

  - name: ibis-pyspark
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pyspark >=3.3.3
        - packaging >=21.3
        - setuptools
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.pyspark

  - name: ibis-sqlite
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - regex >=2021.7.6
        - packaging >=21.3
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.sqlite

  - name: ibis-datafusion
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - datafusion >=0.6
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.datafusion

  - name: ibis-duckdb
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - python-duckdb >=0.8.1
        - pins >=0.8.3
        - fsspec <2024.6.2
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.duckdb

  - name: ibis-pandas
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - python-duckdb >=0.8.1
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.pandas

  - name: ibis-mssql
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - pyodbc >=4.0.39
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.mssql


  - name: ibis-bigquery
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - db-dtypes >=0.3.0,<2
        - google-cloud-bigquery >=3,<4
        - google-cloud-bigquery-storage >=2,<3
        - pydata-google-auth >=1.4.0
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.bigquery

  - name: ibis-trino
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - trino-python-client >=0.321
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.trino

  - name: ibis-snowflake
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - snowflake-connector-python >=3.0.2
        - {{ pin_subpackage(name + '-core', exact=True) }}

    test:
      imports:
        - ibis
        - ibis.backends.snowflake

  - name: ibis-polars
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - packaging >=21.3
        - polars >=0.20.17

    test:
      imports:
        - ibis
        - ibis.backends.polars

  - name: ibis-druid
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - pydruid >=0.6.5
        # we don't require sqlalchemy but pydruid inadvertently requires it
        - sqlalchemy >=1.4

    test:
      imports:
        - ibis
        - ibis.backends.druid

  - name: ibis-oracle
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - oracledb >=1.3.1
        - packaging >=21.3

    test:
      imports:
        - ibis
        - ibis.backends.oracle

  - name: ibis-exasol
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - pyexasol >=0.25.2

    test:
      imports:
        - ibis
        - ibis.backends.exasol

  - name: ibis-flink
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - apache-flink

    test:
      imports:
        - ibis
        - ibis.backends.flink

  - name: ibis-risingwave
    version: {{ version }}

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name + '-core', exact=True) }}
        - psycopg2 >=2.8.4

    test:
      imports:
        - ibis
        - ibis.backends.risingwave


about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: http://www.ibis-project.org
  summary: The portable Python dataframe library

extra:
  recipe-maintainers:
    - jreback
    - xmnlab
    - datapythonista
    - cpcloud
    - gforsyth
