{% set version = "2.0.0" %}

package:
  name: ibis-framework-ext
  version: {{ version }}

source:
  url: https://github.com/ibis-project/ibis/archive/{{ version }}.tar.gz
  sha256: e55178269266c8cd29b68bb5699fdeb251bcf9fdd4957e70a1f9916fd8ab4c18

build:
  number: 1

outputs:

  - name: ibis-framework
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      skip: true  # [py<37]

    requirements:
      host:
        - pip
        - python
        - setuptools
    
      run:
        - cached_property
        - clickhouse-driver >=0.1.3
        - clickhouse-cityhash  # [not win]
        - clickhouse-sqlalchemy
        - geoalchemy2
        - geopandas
        - graphviz
        - impyla >=0.15.0
        - lz4
        - multipledispatch >=0.6
        - numpy >=1.15
        - pandas >=0.25.3
        - parsy
        - psycopg2
        - pyarrow >=0.15
        - pymysql
        - pyspark >=2.4.3
        - pytables >=3.0.0
        - python
        - python-graphviz
        - python-hdfs >=2.0.16
        - pytz
        - regex
        - requests
        - shapely
        - setuptools
        - sqlalchemy >=1.1
        - thrift >=0.11
        - thriftpy2
        - toolz
    
    test:
      imports:
        - ibis
        - ibis.backends.clickhouse
        - ibis.backends.csv
        - ibis.backends.parquet
        - ibis.backends.hdf5
        - ibis.backends.impala
        - ibis.backends.mysql
        - ibis.backends.pandas
        - ibis.backends.postgres
        - ibis.backends.pyspark
        - ibis.backends.sqlite

  - name: ibis-framework-core
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      noarch: python

    requirements:
      host:
        - pip
        - python >=3.7
        - setuptools

      run:
        - multipledispatch >=0.6
        - numpy >=1.15
        - pandas >=0.25.3
        - python >=3.7
        - pytz
        - regex
        - toolz
        - cached_property
        - setuptools
        - parsy
        - python-graphviz

    test:
      imports:
        - ibis
        - ibis.backends.pandas

about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: http://www.ibis-project.org
  summary: Productivity-centric Python Big Data Framework

extra:
  recipe-maintainers:
    - jreback
    - xmnlab
    - datapythonista
