{% set version = "1.0.0" %}

package:
  name: ibis-framework
  version: {{ version }}

source:
  url: https://github.com/ibis-project/ibis/archive/{{ version }}.tar.gz
  sha256: 5fd4652583e618daaff7c2f403ef6e8cd5fbde04b9d8d00d99e88e4c8a14c4e1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3
    - setuptools

  run:
    - clickhouse-driver >=0.0.8
    - google-cloud-bigquery >=1.0.0
    - graphviz
    - impyla >=0.14.2
    - lz4
    - multipledispatch>=0.6
    - numpy >=1.11
    - pandas >=0.20
    - psycopg2
    - pyarrow >=0.12
    - pymapd >=0.8.3
    - pymysql
    - pytables >=3.0.0
    - python >=3
    - python-graphviz
    - python-hdfs >=2.0.16
    - regex
    - setuptools
    - six
    - sqlalchemy
    - thrift
    - thriftpy
    - toolz

test:
  requires:
    - pytest >=3
  imports:
    - ibis
    - ibis.bigquery
    - ibis.bigquery.tests
    - ibis.expr
    - ibis.expr.tests
    - ibis.hive
    - ibis.hive.tests
    - ibis.impala  # [linux]
    - ibis.impala.tests  # [linux]
    - ibis.mapd
    - ibis.mapd.tests
    - ibis.pandas
    - ibis.pandas.tests
    - ibis.spark
    - ibis.spark.tests
    - ibis.sql
    - ibis.sql.postgres
    - ibis.sql.postgres.tests
    - ibis.sql.presto
    - ibis.sql.presto.tests
    - ibis.sql.redshift
    - ibis.sql.redshift.tests
    - ibis.sql.sqlite
    - ibis.sql.sqlite.tests
    - ibis.sql.tests
    - ibis.sql.vertica
    - ibis.sql.vertica.tests
    - ibis.tests

about:
  license: Apache 2.0
  home: http://www.ibis-project.org
  summary: 'Productivity-centric Python Big Data Framework'

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - wesm
    - kszucs
    - xmnlab
