{% set name = "ibis-framework" %}
{% set version = "2.1.1" %}

package:
  name: {{ name }}-ext
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15dc0c5d8abc41a9bddc643b7b360a61195d0363c61e83d2c588c55ff3b5b236

build:
  number: 0

outputs:
  - name: {{ name }}-core
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      noarch: python

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - atpublic >=2.3
        - cached_property >=1
        - importlib-metadata >=4
        - multipledispatch >=0.6
        - numpy >=1.15
        - pandas >=1.2.5
        - python
        - regex >=2021.7.6
        - toolz >=0.11
        - parsy >=1.3.0
        - python-graphviz >=0.16

    test:
      imports:
        - ibis
        - ibis.backends.pandas

  - name: {{ name }}
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - atpublic >=2.3
        - clickhouse-driver >=0.1.3
        - clickhouse-sqlalchemy >=0.1.4
        - datafusion >=0.4
        - geoalchemy2 >=0.6
        - geopandas >=0.6
        - impyla >=0.17
        - psycopg2 >=2.7
        - pyarrow >=1
        - pymysql >=1
        - pyspark >=2.4.3
        - pytables >=3
        - python
        - python-graphviz >=0.16
        - python-hdfs >=2.0.16
        - requests >=2
        - shapely >=1.6
        - sqlalchemy >=1.3
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.clickhouse
        - ibis.backends.csv
        - ibis.backends.parquet
        - ibis.backends.hdf5
        - ibis.backends.impala
        - ibis.backends.mysql
        - ibis.backends.pandas
        - ibis.backends.postgres
        - ibis.backends.pyspark
        - ibis.backends.sqlite
        - ibis.backends.datafusion


  - name: ibis-clickhouse
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - clickhouse-driver >=0.1.3
        - clickhouse-sqlalchemy >=0.1.4
        - sqlalchemy >=1.3
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.clickhouse

  - name: ibis-dask
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - pyarrow >=1
        - dask >=2021.10.0
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.dask

  - name: ibis-hdf5
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - pytables >=3
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.hdf5

  - name: ibis-impala
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - impyla >=0.17
        - python-hdfs >=2.0.16
        - requests >=2
        - sqlalchemy >=1.3
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.impala

  - name: ibis-mysql
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - pymysql >=1
        - sqlalchemy >=1.3
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.mysql

  - name: ibis-parquet
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - pyarrow >=1
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.parquet

  - name: ibis-postgres
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - sqlalchemy >=1.3
        - psycopg2 >=2.7
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.postgres

  - name: ibis-pyspark
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - pyarrow >=1
        - pyspark >=2.4.3
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.pyspark

  - name: ibis-sqlite
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - sqlalchemy >=1.3
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.sqlite

  - name: ibis-datafusion
    version: {{ version }}

    build:
      script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    requirements:
      host:
        - pip
        - python
        - setuptools

      run:
        - datafusion >=0.4
        - python
        - {{ pin_subpackage(name + '-core', max_pin="x.x.x.x") }}

    test:
      imports:
        - ibis
        - ibis.backends.datafusion

about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: http://www.ibis-project.org
  summary: Productivity-centric Python Big Data Framework

extra:
  recipe-maintainers:
    - jreback
    - xmnlab
    - datapythonista
    - cpcloud
    - gforsyth
