# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ibis-framework
  version: "10.8.0"
  python_min: '3.10'
  python_max: '4.0'
  python_test_max: '3.13'

recipe:
  name: ${{ name }}-ext
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace("-", "_") }}-${{ version }}.tar.gz
  sha256: 3cf330c1f786b9d5c425f96df79cc09af7f55c63fd923bd749547c4b1bd03ae4

build:
  number: 1

outputs:
  - package:
      name: ${{ name }}-core
      version: ${{ version }}
    build:
      noarch: python
      script:
        - "find . -iname \"snapshots\" | xargs rm -r && ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check"
    requirements:
      host:
        - pip
        - hatchling
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }},<${{ python_max }}
        - atpublic >=2.3
        - parsy >=2
        - python-dateutil >=2.8.2
        - sqlglot >=23.4,!=26.32.0
        - toolz >=0.11,<1
        - typing-extensions >=4.3.0
        - tzdata>=2022.7
        - packaging>=21.3
      run_constraints:
        - pandas >=1.5.3,<3
        - pyarrow >=10.0.1
        - numpy >=1.23.2,<3
        - packaging >=21.3
        - rich>=12.4.4
        - pyarrow-hotfix >=0.4
    tests:
      - python:
          imports:
            - ibis
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.duckdb
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-clickhouse
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - clickhouse-connect >=0.5.23
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.clickhouse
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-impala
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - impyla >=0.17
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.impala
          pip_check: false
          python_version:
            - ${{ python_min }}.*
  - package:
      name: ibis-mysql
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - mysqlclient >=2.2.4
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.mysql
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-postgres
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - psycopg >=3.2.0,<4
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.postgres
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-pyspark
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - pyspark >=3.3.3,<4
        - packaging >=21.3,<25
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.pyspark
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-sqlite
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - regex >=2021.7.6
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.sqlite
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-datafusion
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - datafusion >=0.6
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.datafusion
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-duckdb
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - python-duckdb >=0.10,!=1.3.0
        - pins >=0.8.3,<1
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
        - packaging >=21.3
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.duckdb
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-mssql
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - pyodbc >=4.0.39
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.mssql
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-bigquery
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - db-dtypes >=0.3.0,<2
        - google-cloud-bigquery >=3,<4
        - google-cloud-bigquery-storage >=2,<3
        - pydata-google-auth >=1.4.0,<2
        - pandas-gbq >=0.26.1
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.bigquery
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-trino
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - trino-python-client >=0.321
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.trino
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-snowflake
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - snowflake-connector-python >=3.0.2
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.snowflake
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-polars
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - polars >=1
        - packaging >=21.3
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.polars
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-druid
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - pydruid >=0.6.7
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.druid
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-oracle
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - oracledb >=1.3.1
        - packaging>=21.3
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.oracle
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-exasol
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - pyexasol >=0.25.2
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.exasol
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-flink
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - apache-flink
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.flink
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-risingwave
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - psycopg2 >=2.8.4,<3
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.risingwave
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-athena
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - pyathena >=3.11.0,<4
        - packaging >=21.3,<25
        - fsspec
        - s3fs
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.athena
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check
  - package:
      name: ibis-databricks
      version: ${{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name + '-core', exact=True) }}
        - databricks-sql-connector >=4.0.0,<5
        - pyarrow >=10.0.1
        - pyarrow-hotfix >=0.4
        - numpy >=1.23.2,<3
        - pandas >=1.5.3,<3
        - rich >=12.4.4
    tests:
      - python:
          imports:
            - ibis
            - ibis.backends.databricks
          pip_check: true
          python_version:
            - ${{ python_min }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script: pip check

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: The portable Python dataframe library
  homepage: http://www.ibis-project.org

extra:
  recipe-maintainers:
    - jreback
    - xmnlab
    - datapythonista
    - cpcloud
    - gforsyth
