appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AavB4c6zbnr9NLZR/J8ULWA0n3eoRIQzINjkVUz8NQIBkpV4wf3t60PnwHXiOOSBLUUVWG8sWdARWHfyu5J/2Vm+mQN050X6KVMCctkAVYz5TcNc9vAFVfESyefMHOYWDE1z6BPiUue3TDnMA6GTb5sLMMbWYJPdoHkrJdwyQCcuMmyo45IPn1Pww7Ftz7D/gfxdiJ1Wz9H6sW0Ce4Smu+vB31EHYucA2chw32sPOujoO0v0WkRwHAxEJcAfxVvoMrKdk5uuzJ0iGfj5d1pVpyB/zwCC+KvZPRq36AIbueYiGg7/in6cAHvCZAPoh5Y60s7d03Zj8s+lcs4XEbzIvyL7jvqTpmKAmM5jWD6tyZaKKaa6P7OXdyhncUZUYXzjNCt/cfGqeOADSpx3yaio4v3/3nXLFeJslxh0U19IUvWsX2funWDOwX4evjRM8jAuBxfGz6SgX79tuaE5pMEHMg2BLdbdPkacPk+M+CCK92WTEimJ1BJDpoXetr9CTR8OD/XsG+aSmbnhNv+w0RpD+IqWThXpkhYPQ1EGJMuCD/2nf859r9gNWQjHcUiKG38CG0gxN03eLHs40CrM2TKJ7dCQg438rKBFtQ4XrvmWbV2ODI3jwPKYAMgIbEOTnDGba5QzMNtHCCaYUHXbP8xdHIPBxfbtV4TFRHZ2WdpYQ5U=}
